	LD HL, 1900H
	LD (HL), 10H
	LD HL, 1901H
	LD (HL), 00H	;DIRECCIÓN DEL ARREGLO

	LD HL, 1902H
	LD (HL), 05H	;NUMERO DE ELEMENTOS
	LD B, (HL)	;CONTADOR

	LD HL, 1900H	;CARGA LA DIRECCION DE LOS DATOS EN DE
	LD D, (HL)
	LD HL, 1901H
	LD E, (HL)
	
ARRAYLOOP:		;LLENADO DEL ARREGLO
	IN A, (00H)
	LD (DE), A
	INC DE
	CP 00H
	DJNZ ARRAYLOOP	

	LD HL, 1902H
	LD B, (HL)
	LD HL, 1900H
	LD D, (HL)
	LD HL, 1901H
	LD E, (HL)
SMALLEST:
	LD A, (DE) 
	

STORE:			;SALIDA DEL DATO
	LD A, (HL)
	OUT (00H), A
	HALT